### PR TITLE
fix validation for cluster configuration, allow unsetting cluster config

### LINKED ISSUE #392: Validate cluster threshold values
Cluster thresholds can currently be set to invalid values >100% and <0% without error messages.

Image

### LINKED ISSUE #393: Allow deleting cluster description
There is no way to remove a cluster description. Once set, the description can only be changed but not deleted.

### PR DESCRIPTION
**Pull request by edlerd**
fixes #393 
fixes #392

image

### CODE REVIEW

File: internal/app/management-api/api/v1/remote_cluster.go [hunk 1]
```diff
@@ -149,28 +149,22 @@ func remoteClusterPatch(rc types.RouteConfig) types.EndpointHandler {
...
-			if payload.MemoryThreshold > 0 {
-				err = store.UpdateRemoteClusterConfig(ctx, tx, store.RemoteClusterConfig{
-					RemoteClusterID: existingRemoteCluster.ID,
-					Key:             store.MemoryThresholdKey,
-					Value:           fmt.Sprintf("%d", payload.MemoryThreshold),
-				})
-				if err != nil {
-					return err
-				}
+			err = store.UpdateRemoteClusterConfig(ctx, tx, store.RemoteClusterConfig{
```
Comment (omarelkashef) [inline internal/app/management-api/api/v1/remote_cluster.go:169]: Why did we leave the validation for the UI?  We can have `if payload.MemoryThreshold >= 0 && payload.MemoryThreshold <= 100` and similarly for DiskThreshold.

File: ui/src/pages/clusters/BulkConfigureClusterPanel.tsx [hunk 2]
```diff
@@ -116,7 +123,7 @@ const BulkConfigureClusterPanel: FC = () => {
                 }}
                 firstValue={clusters[0]?.disk_threshold}
                 defaultValue={80}
-                label="Disk threshold"
+                label="Disk threshold percentage"
```
Comment (omarelkashef) [inline ui/src/pages/clusters/BulkConfigureClusterPanel.tsx:126]: This will break tests from #394. We should make changes according whichever gets merged first.

File: ui/src/pages/clusters/BulkConfigureClusterPanel.tsx [hunk 3]
```diff
@@ -130,6 +137,11 @@ const BulkConfigureClusterPanel: FC = () => {
                   onBlur={formik.handleBlur}
                   onChange={formik.handleChange}
                   value={formik.values.diskThreshold}
+                  error={
+                    formik.touched.diskThreshold
```
Comment (omarelkashef) [inline ui/src/pages/clusters/BulkConfigureClusterPanel.tsx]: `formik.touched.diskThreshold && formik.errors.diskThreshold` is easier?

**Review by omarelkashef — COMMENTED** [review]
Thank you for this PR! A few observations below. I could not do QA because demo server is down.

File: internal/app/management-api/api/v1/remote_cluster.go (hunk 1 above)
Comment (edlerd) [reply internal/app/management-api/api/v1/remote_cluster.go:169]: Right we should keep validation within the suggested limits. Good catch!

File: ui/src/pages/clusters/ConfigureClusterPanel.tsx [hunk 4]
```diff
@@ -137,6 +152,9 @@ const ConfigureClusterPanel: FC = () => {
                 onBlur={formik.handleBlur}
                 onChange={formik.handleChange}
                 value={formik.values.description}
+                error={
+                  formik.touched.description ? formik.errors.description : null
```
Comment (omarelkashef) [inline ui/src/pages/clusters/ConfigureClusterPanel.tsx]: To keep things consistent, `formik.touched.description &&  formik.errors.description`

File: internal/app/management-api/api/v1/remote_cluster.go [hunk 5]
```diff
@@ -149,10 +149,8 @@ func remoteClusterPatch(rc types.RouteConfig) types.EndpointHandler {
 			if payload.Status != "" {
 				newRemoteCluster.Status = string(payload.Status)
 			}
-			if payload.Description != "" {
-				newRemoteCluster.Description = payload.Description
-			}
-			if payload.DiskThreshold > 0 {
+			newRemoteCluster.Description = payload.Description
+			if payload.DiskThreshold >= 0 || payload.DiskThreshold <= 100 {
```
Comment (omarelkashef) [inline internal/app/management-api/api/v1/remote_cluster.go]: Is it intentional to skip and not return err if value is out of range but return err if `UpdateRemoteClusterConfig` returns it?

**Review by omarelkashef — COMMENTED** [review]
Looks good to me, just a questions and nitpick.

File: internal/app/management-api/api/v1/remote_cluster.go (hunk 5 above)
Comment (edlerd) [reply internal/app/management-api/api/v1/remote_cluster.go]: Yes, changing this to do validation first and throw an error if it fails seems like a better approach here.

Comment (omarelkashef) [reply internal/app/management-api/api/v1/remote_cluster.go]: I mean now, we do not return error when validation fails. If user submits an invalid value, they do not get an appropriate error message.

Comment (omarelkashef) [reply internal/app/management-api/api/v1/remote_cluster.go]: Also what about simplifying this block, and updating `newRemoteCluster` with the new values with returning appropriate validation errors and calling `UpdateRemoteClusterConfig` at the end?

Comment (edlerd) [reply internal/app/management-api/api/v1/remote_cluster.go]: The thresholds are custom configurations in another table. Hence, we update them each at a time and can't update them together.  I changed it to validate each before writing and saving the cluster object last.

**Review by omarelkashef — DISMISSED** [review]
Looks great! Thank you

File: internal/app/management-api/api/v1/remote_cluster.go (hunk 5 above)
Comment (omarelkashef) [reply internal/app/management-api/api/v1/remote_cluster.go]: You are right. I confused `UpdateRemoteCluster` with `UpdateRemoteClusterConfig`

**Review by omarelkashef — APPROVED** [review]
Thank you for the new changes!
